### ISSUE TITLE
Option `allow_from_override` broken

### ISSUE THREAD

**Issue by IngoMeyer441** [marlam/msmtp-mirror#119]
Hey and thanks for this nice package. :smile: 

My mail server rejects mail if the from address in envelope and message header do not match my personal mail address. Therefore, I tried to use the `set_from_header on` and `allow_from_override off` options. However, I can still override the from address on the command line with the `-f` switch. I checked the msmtp debug messages and I always get

```
allow_from_override = on
set_from_header = on
```

My config file is

```
# Set default values for all following accounts
defaults
auth                on
tls                 on
tls_trust_file      /etc/ssl/certs/ca-certificates.crt
logfile             ~/.msmtp.log
set_from_header     on

# FZJ
account             fzj
host                mail.fz-juelich.de
port                587
tls_starttls        on
from                i.meyer@fz-juelich.de
allow_from_override off
user                i.meyer@fz-juelich.de

# Set a default account
account default : fzj
```

I don't know if this is related but if I move the `allow_from_override` config line into the `defaults` section, I even get a general msmtp error:

```
msmtp: account default from /home/imeyer/.msmtprc: envelope-from address is missing
```

I am using the latest msmtp version `1.8.23`.

Thanks for the help!

**Comment by marlam** [comment]
You're right, there's a bug: the `allow_from_override` setting was not properly inherited by accounts.
This should be [fixed now](https://git.marlam.de/gitweb/?p=msmtp.git;a=commitdiff;h=af851aa191b40103b469e9f57fb9919ff1374d85) (the fix will appear on the github mirror in a few hours).

However I could not reproduce the `envelope-from address is missing` problem; could you try the patch and see if that problem remains?

**Comment by IngoMeyer441** [comment]
Thanks for your fast response and the quick fix. I can confirm that commit af851aa191b40103b469e9f57fb9919ff1374d85 fixes the setting of `allow_from_override`. The debug output now contains

```
allow_from_override = off
```

:blush: 

But I still get the 

```
msmtp: account default from /home/imeyer/.msmtprc: envelope-from address is missing
```

error. What I did is:

- Change the msmtp configuration to

  ```
  # Set default values for all following accounts
  defaults
  auth                on
  tls                 on
  tls_trust_file      /etc/ssl/certs/ca-certificates.crt
  logfile             ~/.msmtp.log
  set_from_header     on
  allow_from_override off
  
  # FZJ
  account             fzj
  host                mail.fz-juelich.de
  port                587
  tls_starttls        on
  from                i.meyer@fz-juelich.de
  user                i.meyer@fz-juelich.de
  
  # Set a default account
  account default : fzj
  ```
  
- Run the command 
  ```bash
  echo | msmtp "i.meyer@fz-juelich.de"
  ```
  
I know, an empty line is no valid mail :sweat_smile:, but at least it is odd that it is configuration dependent if an error is thrown in this case or not.

Btw: I created an [AUR package for the development version of msmtp](https://aur.archlinux.org/packages/msmtp-git).

**Comment by marlam** [comment]
There was indeed another logic error with `allow_from_override`: since it was set in account `default` (via the defaults section), the account did not inherit the envelope-from address from account `fzj`.
This is now [fixed](https://git.marlam.de/gitweb/?p=msmtp.git;a=commitdiff;h=17eabf3bb474c05ea1ef8b9233fac9e2761073ce) by moving the special handling of `allow_from_override` to the place where the command line options are applied so that it does not affect account inheritance within a configuration file anymore.

**Comment by IngoMeyer441** [comment]
Thanks, I can confirm that `allow_from_override` can now also be placed in the `defaults` section. :partying_face:
