### ISSUE TITLE
.msmtprc: from should accept wildcards, not only `+`

### ISSUE THREAD

**Issue by moviuro** [marlam/msmtp-mirror#46]
Hi,

I suggest that the following be acceptable in a configuration file:

```
account foobar
host barbaz.domain.tld
from user@domain.tld
from user.*@domain.tld # important
auth on
[...]
```

*Why?* Because this allows to send mail easily with "tagged" addresses, such as `user.whatever@domain.tld` (I setup my own domains like that because far too many forms reject the usual `+tag` syntax). This is useful because I could wish to use only an "alias" with my bank (`moviuro.bank@`) and another alias when I exchange with my ISP (`moviuro.isp@`). ATM, I can only send mail as `moviuro@` unless I specify all aliases/alternatives by hand (which would be quite a lot, and would prevent me from using them "on the spot").

I can't write C code, but my guess is that it would require only limited changes to `account_t *find_account_by_envelope_from(list_t *acc_list, const char *from)`.

Best regards,

**Comment by marlam** [comment]
This would require storing multiple `from` addresses per account, and match them all in `find_account_by_envelope_from` with some form of pattern matching or regular expression matching.

I'm not convinced that this is worth it as subadresses are already supported for exactly that purpose. Forms that reject them may be irritating, but they should be fixed instead of worked around; are there really that many of those?

**Comment by moviuro** [comment]
1. Instead of multiple `from=`, using a single one with regex support could do the trick `from=moviuro.*@domain.tld`; or the usual `from=` plus an option `custom_prefix=.-+` (*à la* postfix)
2. Yes, I've stopped using `+` symbols because it's less frustration. Worst case offender was that one time I could subscribe to a newsletter but not unsubscribe because my email was "badly formatted".

**Comment by marlam** [comment]
Hi, I'm leaning towards your suggestion of `custom_prefix` similar to postfix's `recipient_delimiter` in order to not overload the `from` command with too much complexity. However, I currently don't have the time to implement this (even though this is a rather small change); please have a little patience - or if anyone reads this who wants to give it a try: please do :)

**Comment by lheckemann** [comment]
Since I have several aliases for my main address on completely different domains, the `custom_prefix` approach wouldn't cut it for me. @marlam would you be opposed to adding something like a `from_regex` option that allows specifying one regex per account for from addresses? If not I'd take a shot at implementing it.

**Comment by helpinghandindia1** [comment]
Hello there,
We are Helping Hand India NGO .

We tried to send email to our associated students through linux.
We tried with gmail and rediffmail but still not successful.
kindly help


msmtp configure file

#set default values for all following accounts.
defaults
#auth        ntlm
#auth         on
#tls            on
#protocol smtp
tls_starttls on
#tls_trust_file    /etc/pki/tls/certs/ca-bundle.crt
#tls_trust_file    /root/DigiCertHighAssuranceCA-3.crt
#tls_trust_file /etc/ssl/certs/ca-certificates.crt
#tls_trust_file   /etc/pki/tls/cert.pem


logfile        /var/log/msmtp
# rediffmail
#account       freemail.hu
account         rediff

#account default : freemail.hu
account default : rediff

#host           smtp.gmail.com
#host           smtp.freemail.hu
host           smtp.rediffmail.com
#port           587
port           25
#from           anil.sharma.ccs@gmail.com
#from           office@helpinghandindiango.org
from          anilbakhtani1975@rediffmail.com
#from           anilbakhtani@freemail.hu
user           anilbakhtani1975@rediffmail.com
#user           office
password       xxxxxxxxx

**Comment by marlam** [comment]
Sorry for answering so late. A command such as `from_regex` would be useful for your use case and I'm not opposed to it (though I'm not sure about the name).

**Comment by dkrm0** [comment]
@moviuro I encountered the same problem as you and I made a quick & dirty fixes on my fork: https://github.com/dkrm0/msmtp-mirror/tree/feature/envelope-from-wildcard

It works for with `*@domain.tld` and should also works for `user.*@domain.tld`, or even `user*@domain.tld`.

**Comment by lheckemann** [comment]
`fnmatch` won't allow me to specify that I want to use the same account e.g. for both `admin@client1.example.com` and `tech@client2.example.com`, so it won't help me. I guess it would address several other people's use cases though.

**Comment by marlam** [comment]
The following should work for your use case: `from *@*.example.com`.
I have pushed a patch to the main git repository (might take up to 24 hours before it shows up on the Github mirror). Can you try it?

**Comment by lheckemann** [comment]
The trouble is that I do in some cases have different accounts on the same domain, or the same account for addresses on completely different domains. Being able to list multiple match expressions or a regex would solve this. But I suppose to some extent this is a "me problem", which I could also address by fixing my email accounts...

**Comment by marlam** [comment]
The advantage of `fnmatch()` versus regular expressions is that we can easily identify if something is an `fnamtch` pattern: that's the case if it contains `*`, `?` or `[` (according to glob(7)), and these characters cannot be part of mail addresses . So we can easily distinguish that case and don't need an additional command.

For your use case, would it also be acceptable to use something like this?
```
account everything
tls on
[settings]
[more settings]

account domain1matcher : everything
from *@*.example.com
account domain2matcher : everything
from *@*.example.org
account miscmatcher : everything
from some*client*pattern@some*thing.ex???.com
```

**Comment by lheckemann** [comment]
Yes, that would solve my problem wonderfully :)

**Comment by marlam** [comment]
OK, that should already work :)

Then I consider this problem solved (finally; sorry that it took so long).

Please comment and/or re-open if there are still open issues.
